spring.application.name=project-management

spring.datasource.url=jdbc:postgresql://localhost:5432/project_management
spring.datasource.username=postgres
spring.datasource.password=root

api.security.token.secret=${JWT_SECRET:defaultSecretKey}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

springdoc.swagger-ui.path=/docs

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000ms
spring.data.redis.database=0

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
